#########################
#         Kuga          #
#        v 0.0.1        #
#########################

kuga:
  version: "0.0.1"
  autoStart: false

channels:
  message: "Kuga:Message"
  servers: "Kuga:Servers"

jedis:
  hostname: "127.0.0.1"
  password: ""
  database: 1
  port: 6379
  use-password: true

server:
  serverGame: <serverGame>
  serverUUID: <serverUUID>
